//Update(01-Oct-2014): Update for date line. --Mike
var monthNames = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"];

langr = {
    l_knownas: "You are now known as",
    l_isknownas: "is now known as",
    l_connected: "Connected",
    l_reconnecting: "Re-connecting",
    l_disconnected: "Disconnected",
    l_flashwindowenabled: "FlashWindow enabled.",
    l_flashwindowdisabled: "FlashWindow disabled.",
    l_guestpasswordstored: "Guest password stored:",
    l_guestnowbanned: "Guests are now banned!",
    l_guestbanremoved: "Guest ban has been removed!",
    l_mircguestnowbanned: "mIRC Guests are now banned!",
    l_mircgueatbanremoved: "mIRC Guest ban has been removed!",
    l_youareinvited_a: "You have invited",
    l_youareinvited_b: "to this room.",
    l_version: "Version:",
    l_commandlinessupported: "Commandline commands supported in this client:",
    l_commandlinessupported_b: ". Commands must start with /",
    l_guestprefix: "Guest_",
    l_levelprefixstaff: "Staff",
    l_levelprefixsuperowner: "Superowner",
    l_levelprefixowner: "Owner",
    l_levelprefixhost: "Host",
    l_levelprefixhelpop: "Helpop",
    l_userschatting: "users chatting",
    l_userhasjoined: "has joined the conversation.",
    l_userhasleft: "has left the conversation.",
    l_uhavejoined: "You have joined the conversation.",
    l_changestopic: "changes topic to:",
    l_changeswelcome: "changes welcome message to:",
    l_changesdisplaylang: "changes display language to:",
    l_notice: "notice",
    l_noticesoff: "has his/her notices turned off.",
    l_chatroombroadcast: "Chat Room Broadcast:",
    l_serverbroadcast: "Server Broadcast:",
    l_kickedoutby: "has been kicked out by",
    l_youhavebeenkickedoutby: "You have been kicked out by",
    l_kickreason: "Reason:",
    l_localtime: "local time:",
    l_changedmodes: "changed modes",
    l_haschangedmodesto: "has changed your modes to",
    l_accessadd: "Access Add:",
    l_banned: "banned",
    l_inviteonly: "invite only",
    l_roomfull: "room full",
    l_knock: "KNOCK",
    l_knocked_a: "knocked.",
    l_knocked_b: "Message:",
    l_blockedinviteflood: "Blocked invite flood.",
    l_hasinvitedyou: "has invited you to chat room:",
    l_blockedinvite_a: "Blocked invite from",
    l_blockedinvite_b: "for security reason(s).",
    l_enterkey: "Enter room key:",
    l_enterkickmsg: "Enter Kick Message",
    l_enternickname: "Enter_Your_Nickname_Here",
    l_nickmorethan2chrs: "* Nickname must be more than 2 characters.",
    l_whispacceptneeded_a: "Waiting for",
    l_whispacceptneeded_b: "to accept your whispers. Don't send more messages until your whisper request is accepted or",
    l_whispacceptneeded_c: "may not receive your messages.",
    l_whispaccepted: "has accepted your whisper request.",
    l_whispdeclined: "has declined your whisper request.",
    l_whispoff: "has his/her whispers turned off.",
    l_whisperacceptdecline_a: "has sent you whispers",
    l_whisperacceptdecline_b: "accept",
    l_whisperacceptdecline_c: "decline",
    l_whisperacceptdecline_e: "ignore user",
    l_whisperacceptdecline_d: "Message:",
    l_whisperattempt_a: "Whisper attempt by",
    l_whisperattempt_b: "Message:",
    l_whispered: "Whispered:",
    l_whispermax: "[Alert: Instances of whisper windows have exceeded max limit. If you want to open new whispers conversation in new window, then close some whisper windows.",
    l_whisperclose: "has closed whisper window.",
    l_isaway_a: "is away.",
    l_isaway_b: "Reason:",
    l_wentaway_a: "went away.",
    l_wentaway_b: "Reason:",
    l_umarkedaway_a: "You are marked as being away.",
    l_umarkedaway_b: "Away message:",
    l_isback: "is back.",
    l_nolongeraway: "You are no longer marked as being away.",
    l_firefoxcopy: "Firefox doesn't allow copy to clipboard through javascript. To Copy please hold the CTRL button and press the V key.",
    l_nowignoring: "You are now ignoring messages from ",
    l_nolongerignoring: "You are no longer ignoring messages from ",
    l_error: "Error:",
    l_errorsendable: "Error: Cannot send message. You need (+v) to send message in this room.",
    l_errorWWsendable: "Error: Cannot send message, whispering or messaging is turned off (+m/w/x).",
    l_errorWWsendableb: "Error: Cannot send message, guest whispering is turned off (+W).",
    l_errorguestpass: "Error: guest password has forbidden character(s).",
    l_errorslevel: "Error: only users with level superowner can use this command.",
    l_errorsolevel: "Error: you must be owner or superowner to use this command.",
    l_errorhlevel: "Error: only users with level host or above can use this command.",
    l_errorcommand_a: "Error: Command",
    l_errorcommand_b: "is not implemented in this client.",
    l_error403_a: "Error: 403. Room",
    l_error403_b: "does not exist.",
    l_error404: "IRC Error: 404.",
    l_error431: "IRC Error: 431. No nickname given. Please use a nickname to enter chat.",
    l_error432: "IRC Error: 432. The nickname you have used is erroneous. Please use another nickname.",
    l_error433_a: "IRC Error: 433. The nickname",
    l_error433_b: "is already in use. This client will try another nickname; you can change it later with /nick command if the command is not disabled on the server.",
    l_error441: "IRC Error: 441. User",
    l_error442: "IRC Error: 442. Room",
    l_error451: "IRC Error: 451.",
    l_error461: "IRC Error: 461.",
    l_error471_a: "IRC Error: 471. Room",
    l_error471_b: "is full. You cannot join it.",
    l_error473_a: "IRC Error: 473. Room",
    l_error473_b: "is invite only. Only those who have been invited may enter this room.",
    l_error474_a: "IRC Error: 474. You or similar mask is currently banned by a host in this",
    l_error474_b: "chatroom, or banned completely from the chat service due to violations of the Code of Conduct. You may be able to reconnect at a later time.",
    l_error474_c: "<br />NOTE: You are not logged in. Many rooms do not allow guest nicknames. You should try to login and then join this room.",
    l_error475_a: "IRC Error: 475. Room",
    l_error475_b: "is protected with a password. You cannot join it without correct key.",
    l_error927: "IRC Error: 927. Room",
    l_error999: "IRC Error: 999.",
    l_errornouser: "Error: no user selected.",
    l_errorwhisper: "Error: Whisper window creation failed; popup-blocker may have blocked creation of whisper window instance.",
    l_errorwhisperinvalidcommand: "Error: That command is not available in whisper window. Please, use /? to check all the available commands",
    l_errorwhispercommandlines: "Commandline commands supported in whisper window:"
};
